name: tft_guide
description: Source code for the TFT Guide app.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependency injection
  get_it: ^7.6.4

  # Localization
  flutter_localizations:
    sdk: flutter

  # Navigator
  go_router: ^12.1.1

  # State Management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  equatable: ^2.0.5

  # UI
  line_icons: ^2.0.3
  google_nav_bar: ^5.0.6

dev_dependencies:
  # Code generation
  build_runner: ^2.4.6

  # Linter
  cosee_lints: ^0.4.0
  dart_code_metrics: ^5.7.6

  # Localization
  i18n: ^4.0.8

  # Launcher icon
  flutter_launcher_icons: ^0.13.1

  # Splash Screen
  flutter_native_splash: ^2.3.5

  # Test
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  golden_toolkit: ^0.15.0

  # Test coverage
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/divisions/iron/
    - assets/divisions/bronze/
    - assets/divisions/silver/
    - assets/divisions/gold/
    - assets/divisions/platinum/
    - assets/divisions/emerald/
    - assets/divisions/diamond/
    - assets/divisions/master/
    - assets/divisions/grandmaster/
    - assets/divisions/challenger/
    - assets/items/base/
    - assets/items/full/
