targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: lib/static/i18n
          input_file_pattern: .i18n.yaml
          lazy: false
          locale_handling: false
          output_directory: lib/static/i18n
          output_file_name: translations.g.dart
          translation_class_visibility: public
          # TODO: Add obfuscation when https://github.com/slang-i18n/slang/issues/259 is resolved.
          format:
            enabled: true
            width: 80