name: tft_guide
description: Source code for the TFT Guide app.
publish_to: none
version: 1.1.1+3

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Local storage
  shared_preferences: ^2.3.2
  sqlite_async: ^0.11.0
  sqlite3_flutter_libs: ^0.5.24

  # Navigator
  go_router: ^14.0.0

  # Network
  dio: ^5.7.0
  http: ^1.2.2
  supabase_flutter: ^2.6.0

  # State Management
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.2.2
  hydrated_bloc: ^9.1.2

  # UI
  animated_flip_counter: ^0.3.4
  dynamic_color: ^1.7.0
  flutter_animation_progress_bar: ^2.3.1
  flutter_markdown: ^0.7.3+1
  flutter_staggered_grid_view: ^0.7.0
  pinput: ^5.0.0
  skeletonizer: ^1.1.2+1

  # Utils
  clock: ^1.1.1
  collection: ^1.18.0
  equatable: ^2.0.5
  file: ^7.0.0
  get_it: ^8.0.0
  logger: ^2.4.0
  open_filex: ^4.5.0
  path: ^1.9.0
  path_provider: ^2.1.1
  package_info_plus: ^8.0.2
  restart: ^1.0.0+1
  stream_transform: ^2.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  # Code generation
  build_runner: ^2.4.6

  # Linter
  cosee_lints: ^0.7.0
  dart_code_linter: ^1.1.3

  # Localization
  slang_flutter: ^4.1.0
  slang_build_runner: ^4.1.0

  # Splash Screen
  flutter_native_splash: ^2.3.5

  # Test
  flutter_test:
    sdk: flutter
  alchemist: ^0.11.0
  bloc_test: ^9.1.5
  faker: ^2.2.0
  http_mock_adapter: ^0.6.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  mock_supabase_http_client: ^0.0.3
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/app/launcher_icon.webp
    - assets/divisions/iron/
    - assets/divisions/bronze/
    - assets/divisions/silver/
    - assets/divisions/gold/
    - assets/divisions/platinum/
    - assets/divisions/emerald/
    - assets/divisions/diamond/
    - assets/divisions/master/
    - assets/divisions/grandmaster/
    - assets/divisions/challenger/

  fonts:
    - family: TFT
      fonts:
        - asset: assets/fonts/tft.ttf