name: app

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/app.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
          cache-dependency-path: |
            app/android/*.gradle*
            app/android/**/gradle-wrapper.properties

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v4
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
            ~/.asdf/shims
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
      - name: Install asdf
        uses: asdf-vm/actions/install@v4
        # See https://github.com/asdf-vm/actions/issues/445
        if: steps.cache-asdf.outputs.cache-hit != 'true'
      - name: Reshim asdf
        run: asdf reshim

      - name: Cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ./app/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('./app/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - name: Install dependencies
        run: flutter pub get

      - name: Generate i18n
        run: dart run slang generate
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_linter:metrics analyze . --set-exit-on-violation-level=warning
      - name: Run tests
        run: |
          flutter test --coverage --test-randomize-ordering-seed=random --dart-define=CI=true
          dart run test_cov_console --exclude=static,domain/interfaces,injector.dart
      - name: Upload golden test failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-test-failures
          path: app/test/ui/**/failures

      - name: Generate key.properties file
        if: github.event_name == 'workflow_dispatch'
        env:
          KEY_PROPERTIES_FILE: ./android/key.properties
        run: |
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" > ${{ env.KEY_PROPERTIES_FILE }}
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> ${{ env.KEY_PROPERTIES_FILE }}
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> ${{ env.KEY_PROPERTIES_FILE }}
      - name: Generate keystore file
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/tft_guide.jks
      - name: Build APK
        if: github.event_name == 'workflow_dispatch'
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          flutter build apk \
            --release \
            --obfuscate \
            --split-debug-info=./build/app/outputs/symbols \
            --dart-define=supabase_anon_key=$SUPABASE_ANON_KEY \
            --dart-define=supabase_url=$SUPABASE_URL \
            --dart-define=github_owner=${{ github.repository_owner }} \
            --dart-define=github_repo=${{ github.event.repository.name }}
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: TFT Guide APK
          path: app/build/app/outputs/apk/release/tft_guide_release_v*.apk
