name: app

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/app.yaml'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Cache asdf
        uses: actions/cache@v4
        id: asdf_cache
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
      - uses: asdf-vm/actions/install@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        id: flutter_cache
        with:
          path: .dart_tool/
          key: ${{ runner.os }}-${{ hashFiles('app/**/pubspec.lock') }}
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Generate i18n
        run: dart run slang
      - name: Analyze code
        run: flutter analyze
      - name: Run Code metrics
        run: dart run dart_code_linter:metrics analyze . --set-exit-on-violation-level=warning

      - name: Build APK
        if: github.event_name == 'workflow_dispatch'
        run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: TFT Guide APK
          path: build/app/outputs/flutter-apk/app-release.apk
