name: infrastructure

on:
  push:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./infrastructure

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v5

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Setup Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
        run: |
          supabase login --token $SUPABASE_ACCESS_TOKEN
          supabase link --project-ref $PROJECT_ID
          supabase db start

      - name: Run Tests
        run: supabase db test

      - name: Deploy Database
        run: supabase db push --include-seed
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
