name: infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yaml'
  workflow_dispatch:

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

defaults:
  run:
    working-directory: ./infrastructure

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Setup Supabase
        run: |
          supabase login --token $SUPABASE_ACCESS_TOKEN
          supabase link --project-ref $PROJECT_ID
          supabase db start

      - name: Run Tests
        run: supabase db test

      - name: Deploy Database
        run: supabase db push --include-seed
        if: github.event_name == 'workflow_dispatch'
